### ISSUE TITLE
How to add a CRF layer?

### ISSUE THREAD

**Issue by bubbleqi** [asahi417/tner#10]
by observing the prediction output, i found many errors were made by wrong prefix. it is possible that a CRF layer as decoder could solve the problem

**Comment by asahi417** [comment]
Thanks for playing around with the models! Although I agree with that adding CRF layer could improve such an error, unfortunately we do not support CRF as of now since we use huggingface transformers API and I think there's no plan to add CRF classifier instead of linear softmax for now in transformers library https://github.com/huggingface/transformers/issues/444 .

**Comment by asahi417** [comment]
CRF is now available!
